{
  "hash": "d0dc39bba696ccf67c073db15da617a5",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Assignment 2: Who Do We Know the Least About?\"\nsubtitle: \"Measuring uncertainty in American Community Survey data\"\nauthor: \"Emmanuel Sampson\"\ndate: today\nformat:\n  html:\n    toc: true\n    code-fold: false\nexecute:\n  warning: false\n  message: false\n---\n\n\n## Setup\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(tidycensus)\n```\n:::\n\n\n\n\n---\n\n## The question\n\nEvery number the American Community Survey publishes is an estimate drawn from a\nsample, not a count. That means every number comes with a margin of error — a\nstatement about how wrong it might be.\n\nMost people ignore it. In this assignment, you won't.\n\n---\n\n## Choosing what to measure\n\n\n```r\nvars <- load_variables(2023, \"acs5\")\nView(vars)\n```\n\nThen use the search box.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmy_state <- \"CO\"        # two-letter abbreviation, in quotes\nmy_variable <- \"B25077_001\"     # the variable code, in quotes\n```\n:::\n\n\n## Pulling the data\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncounty_data <- get_acs(\n  geography = \"county\",\n  variables = my_variable,\n  state = my_state,\n  year = 2023,\n  survey = \"acs5\"\n)\n```\n:::\n\n\nLet's look at what came back.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndim(county_data)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 64  5\n```\n\n\n:::\n\n```{.r .cell-code}\nhead(county_data)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 5\n  GEOID NAME                       variable   estimate   moe\n  <chr> <chr>                      <chr>         <dbl> <dbl>\n1 08001 Adams County, Colorado     B25077_001   458400  3021\n2 08003 Alamosa County, Colorado   B25077_001   218800 21223\n3 08005 Arapahoe County, Colorado  B25077_001   526000  5958\n4 08007 Archuleta County, Colorado B25077_001   451400 16410\n5 08009 Baca County, Colorado      B25077_001   122000 22458\n6 08011 Bent County, Colorado      B25077_001   137900 26527\n```\n\n\n:::\n:::\n\n\n\nThere are 64 counties in Colorado and that number matches the rows returned by dim(country_data) which is 5.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncounty_data <- county_data %>%\n  mutate(moe_pct = moe/estimate * 100)\n```\n:::\n\n\n\n\nNow sort to see which counties are measured least reliably.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncounty_data %>%\n  arrange(desc(moe_pct)) %>%\n  select(NAME, estimate, moe, moe_pct) %>%\n  head(10)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 10 × 4\n   NAME                        estimate    moe moe_pct\n   <chr>                          <dbl>  <dbl>   <dbl>\n 1 Jackson County, Colorado      250000 104968    42.0\n 2 San Miguel County, Colorado   613100 165694    27.0\n 3 San Juan County, Colorado     406900  93791    23.1\n 4 Kiowa County, Colorado        148600  30604    20.6\n 5 Bent County, Colorado         137900  26527    19.2\n 6 Baca County, Colorado         122000  22458    18.4\n 7 Lake County, Colorado         401300  67434    16.8\n 8 Cheyenne County, Colorado     187100  31159    16.7\n 9 Saguache County, Colorado     200000  30566    15.3\n10 Huerfano County, Colorado     256700  37763    14.7\n```\n\n\n:::\n:::\n\n\nJackson County, Colorado has the largest margin of error relative to its estimate.Jackson County’s ACS median home-value estimate has a margin of error equal to about 42% of the estimate, making it the least precise estimate in the displayed set.\n\n## Sorting counties into reliability categories\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncounty_data <- county_data %>%\n  mutate(reliability = case_when(\n    moe_pct < 5  ~ \"High confidence\",\n    moe_pct < 10 ~ \"Moderate\",\n    TRUE         ~ \"Low confidence\"\n  ))\n\ncount(county_data, reliability)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 2\n  reliability         n\n  <chr>           <int>\n1 High confidence    23\n2 Low confidence     21\n3 Moderate           20\n```\n\n\n:::\n:::\n\n\nI evaluated the reliability of ACS estimates for median owner-occupied home values across Colorado counties by calculating each estimate’s margin of error as a percentage of its reported value: (MOE/estimate)×100.Counties with a relative MOE below 5% were classified as high confidence, those between 5% and 10% as moderate confidence, and those above 10% as low confidence. These thresholds are interpretive rather than official Census reliability standards, but they create a useful distribution for this county-level analysis: 23 counties have high-confidence estimates, 20 have moderately reliable estimates, and 21 have low-confidence estimates.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncounty_wide <- get_acs(\n  geography = \"county\",\n  variables = c(myvar = my_variable,\n                pop   = \"B01003_001\"),\n  state = my_state,\n  year = 2023,\n  survey = \"acs5\",\n  output = \"wide\"\n)\n\nhead(county_wide)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 6\n  GEOID NAME                       myvarE myvarM   popE  popM\n  <chr> <chr>                       <dbl>  <dbl>  <dbl> <dbl>\n1 08001 Adams County, Colorado     458400   3021 524408    NA\n2 08003 Alamosa County, Colorado   218800  21223  16515    NA\n3 08005 Arapahoe County, Colorado  526000   5958 655709    NA\n4 08007 Archuleta County, Colorado 451400  16410  13730    NA\n5 08009 Baca County, Colorado      122000  22458   3460    NA\n6 08011 Bent County, Colorado      137900  26527   5524    NA\n```\n\n\n:::\n:::\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncounty_wide <- county_wide %>%\n  mutate(moe_pct = myvarM / myvarE * 100) %>%\n  mutate(reliability = case_when(\n    moe_pct < 5  ~ \"High confidence\",\n    moe_pct < 15 ~ \"Moderate\",\n    TRUE         ~ \"Low confidence\"\n  ))\n```\n:::\n\n\nNow compare the average population of counties in each reliability category.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncounty_wide %>%\n  group_by(reliability) %>%\n  summarize(\n    n_counties = n(),\n    avg_population = mean(popE)\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 3\n  reliability     n_counties avg_population\n  <chr>                <int>          <dbl>\n1 High confidence         23        234182.\n2 Low confidence           9          4015.\n3 Moderate                32         12139.\n```\n\n\n:::\n:::\n\n\n\nHigh-confidence counties have an average population of approximately 234,182 people, compared with about 4,015 people in low-confidence counties. Moderate-reliability counties have an average population of approximately 12,139 people. This pattern suggests that, in this dataset, more populous counties generally have more precise ACS median home-value estimates, while less populous counties tend to have larger relative margins of error and lower-confidence estimates.\n\n## What this means for policy\n\nColorado communities with the least reliable ACS estimates of median owner-occupied home values are primarily small, rural counties. Jackson County has the greatest uncertainty: its estimated median home value is $250,000, with a margin of error of ±$104,968, or 42.0% of the estimate. Other counties with relatively high uncertainty include San Miguel County (27.0%), San Juan County (23.1%), Kiowa County (20.6%), Bent County (19.2%), and Baca County (18.4%). Using the selected thresholds, nine counties fall into the low-confidence category, compared with 23 high-confidence and 32 moderate-reliability counties.\n                                                                              \nThis pattern reflects how the American Community Survey (ACS) works. Unlike a complete census count, the ACS is a continuous sample survey. Its estimates are based on responses from a subset of households rather than every household. Smaller counties contain fewer households and therefore tend to produce smaller survey samples. Smaller samples create more sampling variability, which appears as a larger margin of error relative to the reported estimate. ACS sampling error is generally lower when the sample size is larger, while small-area estimates often require pooled multi-year data to achieve usable precision.\n\n\nA state agency that allocates housing assistance, property-tax relief, or infrastructure funding based on median home values—but treats every county estimate as equally precise—could make poorly targeted decisions. Rural, low-population counties would be most vulnerable. For example, Jackson County could be classified as comparatively high-value or low-value based on an estimate with a confidence interval spanning roughly $145,032 to $354,968. Funding formulas that ignore this uncertainty could underfund communities with genuine housing need or direct funds away from them based on unstable measurements. Agencies should therefore incorporate MOEs, confidence intervals, or reliability flags when comparing counties and making resource-allocation decision.\n\n\n**Reflections**\n\nWhen assessing estimates of median owner-occupied home values, it is important to consider margins of error and confidence intervals, as these measures provide greater context for informed policy-making. Relying solely on arbitrary or point estimates may lead to misleading conclusions and ineffective policy decisions. Counties seeking to implement policies that produce meaningful change should therefore account for the uncertainty surrounding these estimates when evaluating housing conditions and allocating resources.\n\n\n\n\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}